# Declare variables to be passed into your templates.
nameOverride: ""
fullnameOverride: ""

image:
  repository: repository/phoenix:latest
  tag: latest
  pullPolicy: Always

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"  
  hosts:
    - chart-example.local

internal:
  replicaCount: 1

  service:
    type: ClusterIP
    port: 8081

  data:
    # all the env variables can be found here: https://github.com/rtlnl/phoenix/blob/master/cmd/internal.go#L64
    DB_HOST: "redis-master.phoenix:6379"
    DB_PASSWORD: ""
    S3_REGION: "us-west-1"
    S3_ENDPOINT: "s3.eu-west-1.amazonaws.com"
    S3_DISABLE_SSL: "false"

  resources: {}
  nodeSelector: {}
  tolerations: {}
  affinity: {}

public:
  replicaCount: 1

  service:
    type: ClusterIP
    port: 8082

  data:
    DB_HOST: "redis-master.phoenix:6379"
    DB_PASSWORD: ""
    # Other ENV you can set in the configmap
    # You can find all the possible variables here: https://github.com/rtlnl/phoenix/blob/master/cmd/public.go#L102
    # REC_LOGS_TYPE: "kafka"
    # REC_LOGS_BROKERS: "kafka-broker-0:9092,kafka-broker-1:9092,kafka-broker-3:9092"
    # REC_LOGS_TOPIC: "my.topic"
    # REC_LOGS_SASLMECHANISM: "PLAIN"
    # GIN_MODE: "release"

  secrets: {}
    # env variables that you would store as secret
    # REC_LOGS_USERNAME: "dXNlcm5hbWU="
    # REC_LOGS_PASSWORD: "cGFzc3dvcmQ="
  resources: {}
  nodeSelector: {}
  tolerations: {}
  affinity: {}

worker:
  replicaCount: 1  

  data:
    # all the env variables can be found here: https://github.com/rtlnl/phoenix/blob/master/cmd/worker.go#L79
    WORKER_BROKER_URL: "edis-master.phoenix:6379"
    WORKER_PASSWORD: ""

  resources: {}
  tolerations: {}
  affinity: {}

redis:
  enabled: true
  resources: {}
    # cpu: 100m
    # memory: 100Mi 
