apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api.fullname" . }}-internal
  labels:
    app.kubernetes.io/name: {{ include "api.name" . }}-internal
    helm.sh/chart: {{ include "api.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.internal.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "api.name" . }}-internal
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "api.name" . }}-internal
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["internal"]
          envFrom:
            - configMapRef:
                name: {{ include "api.fullname" . }}-internal
          ports:
            - name: http
              containerPort: {{ .Values.internal.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.internal.resources | indent 12 }}
      affinity:
{{ toYaml .Values.internal.affinity | indent 8 }}
      tolerations:
{{ toYaml .Values.internal.tolerations | indent 8 }}      
      nodeSelector:
{{ toYaml .Values.internal.nodeSelector | indent 8 }}
