apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api.fullname" . }}-public-secret
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "api.name" . }}-public
    helm.sh/chart: {{ include "api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{- if .Values.public.secrets }}
{{ toYaml .Values.public.secrets | indent 2 }}
{{- end }}