version: "2"

services:
  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "4572:4572"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=eu-west-1
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME=localstack
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - ./.localstack:/tmp/localstack

  redis:
    image: redis
    container_name: redis
    command: ["redis-server", "--appendonly yes"]
    ports:
      - "6379:6379"

  phoenix:
    build:
      context: ../
      dockerfile: Dockerfile.tests
    container_name: phoenix
    environment:
      - DB_HOST=redis:6379
      - S3_ENDPOINT=localstack:4572
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
    depends_on:
      - redis
      - localstack
    command: "go test -race ./..."