version: "2"

services:
  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "4572:4572"
      - "8080:8080"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=eu-west-1
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./.localstack:/tmp/localstack

  redis:
    image: redis
    container_name: redis
    command: ["redis-server", "--appendonly yes"]
    ports:
      - "6379:6379"

  phoenix:
    image: 451291743503.dkr.ecr.eu-west-1.amazonaws.com/phoenix:tmp-dev
    container_name: phoenix
    depends_on:
      - redis
      - localstack
    command: "go test -race ./..."