resource_types:
- name: sonar-runner
  type: docker-image
  source:
    repository: cathive/concourse-sonarqube-resource
    tag: latest

resources:
- name: git-repo
  type: git
  icon: github-circle
  source:
    uri: git@github.com:rtlnl/data-personalization-api.git
    branch: master
    private_key: ((github_private_key))

- name: ecr-docker-reg
  type: docker-image
  source:
    aws_access_key_id: ((ecr_access_key_id))
    aws_secret_access_key: ((ecr_secret_access_key))
    repository: ((ecr_repository))/data-personalization-api
    tag: prod

- name: code-analysis
  type: sonar-runner
  source:
    host_url: https://sonarqube-controlplane.rtl-di.nl/
    login: ((personalization_api_sonarqube_auth_token))
    project_key: data-personalization-api

jobs:
- name: build-and-analyze
  plan:
  - get: git-repo
    trigger: true
  - in_parallel:
    - put: code-analysis
      params:
        project_path: git-repo
        project_key: data-personalization-api
        additional_properties:
          sonar.javascript.lcov.reportPaths: coverage/coverage.out
      get_params:
        quality_gate:
          ignore_errors: ['new_coverage', 'violations']
          ignore_warns: ['new_duplicated_lines_density', 'violations']

- name: build
  public: false
  plan:
  - get: git-repo
    trigger: true
  
  # need to find a way to have aerospike and localstack in concourse
  # for running integration tests
  
  # - task: run-tests
  #   config:
  #     platform: linux
  #     image_resource:
  #       type: registry-image
  #       source: {repository: golang}
  #     inputs:
  #       - name: git-repo
  #     run:
  #       path: /bin/sh
  #       args:
  #         - -c
  #         - |
  #           go get -t -v ./...
  #           go test -v ./...

    # release the image if the tests are successful
  - put: ecr-docker-reg
    params:
      build: git-repo
