resources:
  - name: git-repo
    type: git
    icon: github-circle
    source:
      uri: git@github.com:rtlnl/phoenix.git
      branch: master
      private_key: ((github_private_key))

  - name: ecr-docker
    type: docker-image
    source:
      aws_access_key_id: ((ecr_access_key_id))
      aws_secret_access_key: ((ecr_secret_access_key))
      repository: ((ecr_repository))/phoenix
      tag: prod

  - name: redis
    type: docker-image
    source:
      repository: redis
      tag: alpine

  - name: localstack
    type: docker-image
    source:
      repository: localstack/localstack
      tag: 0.10.5

jobs:
  - name: integration
    plan:
      - in_parallel:
          - get: git-repo
            trigger: true
          - get: redis
            params: { save: true }
          - get: localstack
            params: { save: true }
      - task: Run integration tests
        privileged: true
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: amidos/dcind
              tag: 2.0.0
          inputs:
            - name: git-repo
            - name: redis
            - name: localstack
          run:
            path: bash
            args:
              - -exc
              - |
                source /docker-lib.sh
                start_docker

                # Preloading of Docker images
                docker load -i redis/image
                docker load -i localstack/image

                # Run the container with tests and its dependencies.
                docker-compose -f git-repo/ci/integration.yaml run --rm phoenix

                # Cleanup.
                docker-compose -f git-repo/ci/integration.yaml down
                docker volume rm $(docker volume ls -q)
      - put: ecr-docker
        params:
          build: git-repo
