resource_types:
  - name: sonar-runner
    type: docker-image
    source:
      repository: cathive/concourse-sonarqube-resource
      tag: latest

resources:
  - name: git-repo
    type: git
    icon: github-circle
    source:
      uri: git@github.com:rtlnl/data-personalization-api.git
      branch: master
      private_key: ((github_private_key))

  - name: ecr-docker-reg
    type: docker-image
    source:
      aws_access_key_id: ((ecr_access_key_id))
      aws_secret_access_key: ((ecr_secret_access_key))
      repository: ((ecr_repository))/data-personalization-api
      tag: prod

  - name: code-analysis
    type: sonar-runner
    source:
      host_url: https://sonarqube-controlplane.rtl-di.nl/
      login: ((personalization_api_sonarqube_auth_token))
      project_key: data-personalization-api
      branch_name: master

jobs:
  - name: run tests
    plan:
      - get: git-repo
        trigger: true
      - task: build
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: golang, tag: 1.12 }
          inputs:
            - name: git-repo
              path: /go/src/github.com/rtlnl/data-personalization-api
          run:
            path: /bin/sh
            # TODO: find a way to have aerospike and localstack in concourse
            args:
              - -c
              - |
                SRCPATH=$PWD/go/src/github.com/rtlnl/data-personalization-api
                GOPATH=$PWD/go
                cd $SRCPATH
                export GO111MODULE=on
                go get -t -v ./...
                # go test -v ./...

      - put: ecr-docker-reg
        params:
          build: git-repo
